apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-llm
  namespace: honest-orchestration
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ollama-llm
  template:
    metadata:
      labels:
        app: ollama-llm
    spec:
      containers:
      - env:
        - name: OLLAMA_HOST
          value: 0.0.0.0
        - name: OLLAMA_ORIGINS
          value: '*'
        image: ollama/ollama:latest
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 10 && ollama pull codellama:7b && ollama pull llama3.1:8b
        name: ollama
        ports:
        - containerPort: 11434
        resources:
          limits:
            cpu: 4000m
            memory: 8Gi
          requests:
            cpu: 2000m
            memory: 4Gi
        volumeMounts:
        - mountPath: /root/.ollama
          name: ollama-data
      volumes:
      - emptyDir: {}
        name: ollama-data
